 function cellInfo = ProjectBuses(varargin) 

cellInfo = { ...
    { ...
    'CANInputStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'Pin101_Pin104_CMD',                    1,      'PinInputStruct',                      -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;

cellInfo = { ...
    { ...
    'CANOutputStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'Pin101_Pin104_FB',                    1,      'PinFBStruct',                      -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;

cellInfo = { ...
    { ...
    'PinInputStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'PinCMD',                    1,      'PinCMDStruct',                      -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PinCFG',                    1,      'PinCFGStruct',                      -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;

cellInfo = { ...
    { ...
    'PinCMDStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'Pin0_value',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin1_value',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin2_value',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin3_value',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;

cellInfo = { ...
    { ...
    'PinCFGStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'Pin0_config',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin1_config',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin2_config',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin3_config',      1,      'uint8',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;

cellInfo = { ...
    { ...
    'PinFBStruct', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
{'Pin0_feedback',      1,      'uint16',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin1_feedback',      1,      'uint16',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin2_feedback',      1,      'uint16',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pin3_feedback',      1,      'uint16',                             -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    }';

Simulink.Bus.cellToObject(cellInfo) ;
clear cellInfo;
